# Generated by Django 4.1.6 on 2023-03-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0001_initial'),
        ('account', '0002_userstype_otp_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userSB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RX.scientificoffice'),
        ),
    ]
