# Generated by Django 4.1.6 on 2023-02-21 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('License', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('ManufactureName', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScientificOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('License', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScientificOfficeItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('ProductName', models.CharField(max_length=100)),
                ('ChemicalName', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=50)),
                ('Package', models.CharField(max_length=50)),
                ('ProductDate', models.DateField()),
                ('ExpireDate', models.DateField()),
                ('BatchNumber', models.CharField(max_length=50)),
                ('ManufactureID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RX.manufactures')),
                ('ScientificOfficeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RX.scientificoffice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScientificOfficeStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductDate', models.DateField()),
                ('ExpireDate', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RX.scientificofficeitems')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('InvoiceNumber', models.IntegerField()),
                ('InvoiceDate', models.DateTimeField(auto_now=True)),
                ('PaymentTerms', models.PositiveIntegerField(default=0)),
                ('ContactDetails', models.CharField(blank=True, max_length=100, null=True)),
                ('DueDate', models.DateField()),
                ('Quantitiy', models.PositiveIntegerField()),
                ('SellPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('InvoiceDW', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RX.distributorwarehouse')),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RX.scientificofficestock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
