# Generated by Django 4.1.6 on 2023-03-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0002_alter_invoices_invoicedw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='InvoiceDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
