# Generated by Django 4.1.6 on 2023-03-07 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0003_alter_invoices_invoicedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('invoice', models.ManyToManyField(related_name='invoice_order', to='RX.invoices')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
