# Generated by Django 4.1.6 on 2023-03-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0005_remove_order_invoice_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderDW',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RX.distributorwarehouse'),
        ),
    ]
