# Generated by Django 4.1.6 on 2023-03-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0006_order_orderdw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Invoice',
            new_name='Invoices',
        ),
    ]
