# Generated by Django 4.1.6 on 2023-03-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RX', '0007_rename_invoice_order_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Invoices',
        ),
        migrations.AddField(
            model_name='order',
            name='Invoices',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoice_order', to='RX.invoices'),
        ),
    ]
